site_name: npc-engine
site_url: https://npc-engine.com/
repo_url: https://github.com/npc-engine/npc-engine
theme:
  name: "material"
  logo: "resources/settings.svg"
  favicon: "resources/fav.svg"
  palette:
    primary: black
    accent: yellow
  features:
    - header.autohide
    - navigation.instant
    - navigation.tabs
    - navigation.sections
nav:
  - Home: index.md
  - Inference Engine:
      - Overview: inference_engine/overview.md
      - Running The Server: inference_engine/running_server.md
      - Build From Source: inference_engine/building.md
      - Exporting models: inference_engine/exporting_models.md
      - API Classes: inference_engine/api_classes.md
      - Services: inference_engine/models.md
      - Reference: inference_engine/reference.md
extra:
  version:
    provider: mike
    default: stable
  social:
    - icon: fontawesome/brands/discord
      link: "https://discord.gg/R4zBNmnfrU"
    - icon: fontawesome/brands/patreon
      link: "https://www.patreon.com/npcengine"
    - icon: fontawesome/brands/unity
      link: "https://assetstore.unity.com/packages/tools/ai/npc-engine-208498"
    - icon: fontawesome/brands/youtube
      link: "https://www.youtube.com/channel/UCOtXe2JwUTHXrA4V9DwANlQ"
    - icon: fontawesome/regular/envelope
      link: mailto:hello@npc-engine.com
    - icon: fontawesome/brands/github
      link: https://github.com/npc-engine
plugins:
  - mike
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          rendering:
            heading_level: 3
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  - attr_list
  - abbr
  - pymdownx.snippets
extra_css:
  - css/style.css
