model_type: "BartChatbot"
max_steps: 128
min_length: 2
repetition_penalty: 1
template_string: >
  {{ persona }}
  {% for line in history -%}
  {{line}}
  {%- endfor %}
default_context: >
  {
    "persona": "",
    "history": ["", ""]
  }

bos_token_id: 0
eos_token_id: 2
pad_token_id: 1
